export type ProjectType = {
    datetime: string;
    title: string;
    shorttitle: string;
    images: string[];
    description: string;
    url: string | null;
    code_url: string | null;
    links: string[];
    features: string[];
    tech: string[];
    category: string;
}

export const projects: ProjectType[] = [
    {
        "datetime": "2023-10-01",
        "title": "Arabic to Emirati Sign Language",
        "shorttitle": "esl",
        "images": ["/project-images/esl/1.jpg", "/project-images/esl/2.jpg"],
        "description": "Emirati Sign Language (ESL) is a visual language used by hard of hearing Emiratis to communicate. It is produced by body, face, and gestures of the hands. Akin to spoken languages, each country has its own sign language that the hard of hearing use. Building a translation system that can generate real-time signing avatar is extremely helpful to build accessible spaces. This system is a first of its kind AI based generative translation system from Arabic text to Emirati sign language. In this paper, we present a first version of our generative translation system, it uses LLMs, tokenization and embeddings to extract the morphological properties of each word of the input sentence and convert it into the appropriate ESL sentence. Then it generates a video sequence representing the sentence in Emirati sign language from a curated database of ESL signs. During the translation, if a word in the sentence is a proper noun or does not have a corresponding entry in the database, it will be finger spelled. The efficacy of the solution is measured by calculating the BLEU score across various examples. We have patented this solution and won multiple competitions with the same.",
        "url": null,
        "code_url": null,
        "links": ["https://drive.google.com/file/d/1mBfR3GCZCFYzkVp_u8PIL0aebBgN9av0/view?usp=sharing", "https://docs.google.com/presentation/d/19JviRxtBXDuzy83eqo6Jg1h3t6vWfyJTyq1MBcs6fTI/edit?usp=sharing", "https://drive.google.com/file/d/1-TcI7NGs5RTwfRekuJTmlgmVEaGsRINn/view"],
        "features": ["Highly accurate translation", "Finger spelling for unknown words", "One of a kind solution for ESL"],
        "tech": ["Python", "GPT-3.5 API", "Streamlit"],
        "category": "Website"
    },
    {
        "datetime": "2023-05-01",
        "title": "BITSA - BITS Assistant",
        "shorttitle": "bitsa",
        "images": ["/project-images/bitsa/1.jpg", "/project-images/bitsa/2.jpg"],
        "description": "*Website not active - API is no longer linked* BITSA is a conversational AI system designed to assist students and faculty at BITS Pilani, Dubai Campus. The chatbot provides information on various topics, including academics, events, and campus facilities. It is built using the Rasa framework and can be accessed through the BPDC website or messaging platforms like Facebook Messenger and WhatsApp. The chatbot is designed to provide quick and accurate responses to user queries, enhancing the overall user experience.",
        "url": "https://bitsa.pythonanywhere.com/",
        "code_url": "https://github.com/Fir121/bpdc_gpt_chatbot",
        "links": ["https://drive.google.com/file/d/1ek0TdOn1kRfJs1AUCM9HtOIpgGzvvx-i/view?usp=drive_link", "https://docs.google.com/presentation/d/1AHBSMXRLRBsRqm58ofQ8cGb0T7wiAbC3SOB19rCeFgU/edit?usp=sharing"],
        "features": ["Familiar, clean and friendly user interface", "Designed for concurrency", "Highly accurate responses by using strong data storage and retreival methods", "Take user feedback for future manual finetuning"],
        "tech": ["Python", "GPT-3.5 API", "Flask", "HTML", "CSS", "JavaScript"],
        "category": "Website"
    },
    {
        "datetime": "2023-10-01",
        "title": "AluminEye",
        "shorttitle": "alumineye",
        "images": ["/project-images/alumineye/1.jpg", "/project-images/alumineye/2.jpg"],
        "description": "AluminEye is an innovative social media application designed to bring together the alumni of BPDC. Alumni seek to remember and relive their college days and memories yet cannot find any easy or engaging way to do so. Several terabytes of images and data go to waste since no significant insights can be generated. Collecting data about Alumni and Students is a difficult task that requires heavy manual labour. AluminEye solves all these problems by providing a platform for alumni to connect, share memories, and stay updated on the latest news and events at BPDC. The application also uses AI to process images and detect faces, allowing users to seamlessly relive their college days",
        "url": null,
        "code_url": "",
        "links": ["https://drive.google.com/file/d/1983utX0GF_r5Nrmiuugjs9U9i8M5IvMh/view?usp=sharing"],
        "features": ["Curated User Feed", "Social Interactions - Likes, Comments", "AI Facial Recognition", "User Feedback to finetune the AI model's results", "Fun and engaging Puzzle Game to keep users engaged", "Admin Panel to manage pictures and posts"],
        "tech": ["Flutter", "Python", "Flask", "Google APIs"],
        "category": "App"
    },
    {
        "datetime": "2023-12-01",
        "title": "Ethereum Based Voting",
        "shorttitle": "ethervoter",
        "images": ["/project-images/ethervoter/1.jpg"],
        "description": "A Solidity smart contract that allows for secure and transparent voting on the Ethereum blockchain. The contract is designed to be simple and easy to use, ensuring that votes are recorded accurately and cannot be tampered with. This project demonstrates the potential of blockchain technology to revolutionize voting systems by providing a decentralized and trustless platform for conducting elections. A research paper is attached",
        "url": null,
        "code_url": "https://github.com/Fir121/voting-on-the-blockchain",
        "links": ["https://docs.google.com/document/d/1krPYKRcxFrOlRZppslc9BWK55h_n8Y6v0g9BJbsqERc/edit?usp=sharing"],
        "features": ["Simple contract", "Secure and simple Voting"],
        "tech": ["Solidity", "Ethereum"],
        "category": "Other"
    },
    {
        "datetime": "2024-04-01",
        "title": "BPDC Map Navigator",
        "shorttitle": "bpdcnavigator",
        "images": ["/project-images/bpdcnavigator/1.jpg"],
        "description": "A simple navigator application to help students and teachers navigate the BPDC campus. The application is built using Streamlit and GeoJSON data to provide an interactive map of the campus. Users can search for buildings, view their location on the map, and get directions to their destination, the directions are generated using the A star algorithm to find the shortest path between two points.",
        "url": "https://bpdcnavigator.streamlit.app/",
        "code_url": "https://github.com/Fir121/college-map-navigation-system",
        "links": [],
        "features": ["Simple interface", "Easy to adapt to any campus or building"],
        "tech": ["Python", "Streamlit", "GeoJSON"],
        "category": "Website"
    },
    {
        "datetime": "2023-07-01",
        "title": "GradeScale",
        "shorttitle": "gradescale",
        "images": ["/project-images/gradescale/1.jpg", "/project-images/gradescale/2.jpg", "/project-images/gradescale/3.jpg"],
        "description": "Grading essays is a time-consuming task for university professors, often leading to delays in providing feedback to students. Additionally, subjective biases may influence grading consistency. To address these challenges, GradeScale is an automated essay grading system powered by Natural Language Processing (NLP) techniques. This system enables professors to efficiently assess students' essays, provide timely feedback, and identify areas for improvement, ultimately enhancing the grading process and learning outcomes.",
        "url": null,
        "code_url": "https://github.com/Fir121/nlp-project",
        "links": ["https://github.com/Fir121/nlp-project/wiki", "https://drive.google.com/file/d/1BIEH92pJxMITkQg7y5gttf7W6w45ohQk/view?usp=sharing"],
        "features": ["Verified Student and Teacher Accounts", "Automated Essay Grading", "Detailed Feedback Reports", "Customisable Grading Criteria"],
        "tech": ["Flask", "Python", "HTML", "CSS", "JavaScript", "NLP"],
        "category": "Website"
    },
    {
        "datetime": "2023-07-01",
        "title": "ACM GMeet Recorder Bot",
        "shorttitle": "acmgmeetrec",
        "images": ["/project-images/acmgmeetrec/1.jpg"],
        "description": "This script uses selenium to automate the process of recording Google Meet sessions. It can be used to record lectures, meetings, or any other Google Meet session. The script can be run on a server to record sessions automatically, by simply inviting the relevant account",
        "url": null,
        "code_url": null,
        "links": [],
        "features": ["Automatic Google Drive video upload", "High quality video recording", "Configured to leave the meet when there are no participants"],
        "tech": ["Google APIs", "Python", "Linux"],
        "category": "Other"
    },
    {
        "datetime": "2024-07-01",
        "title": "ACM Portal",
        "shorttitle": "acmportal",
        "images": ["/project-images/acmportal/1.jpg", "/project-images/acmportal/2.jpg", "/project-images/acmportal/3.jpg"],
        "description": "The ACM Portal is a webApp built for the ACM chapter of BITS Pilani, Dubai Campus. The portal is a one-stop solution for all ACM related activities, including event management, membership management, and a posts forum for the BPDC ACM chapter. The portal is built to be highly configurable, allowing the admin to add, edit and delete events, members, certificates and posts as needed.",
        "url": "https://portal.acmbpdc.org",
        "code_url": null,
        "links": [],
        "features": ["Clean simple UI", "QR Code verified certificates", "Member Exclusive content", "Separate admin panel with detailed statistics and reports", "Customizable permissions for each user", "Well integrated with Google OAuth to speed up membership applications"],
        "tech": ["Next.JS", "Python", "Django", "Typescript"],
        "category": "Website"
    },
    {
        "datetime": "2023-08-01",
        "title": "CBee.AI",
        "shorttitle": "cbee",
        "images": ["/project-images/cbee/1.jpg", "/project-images/cbee/2.jpg", "/project-images/cbee/3.jpg", "/project-images/cbee/4.jpg", "/project-images/cbee/5.jpg", "/project-images/cbee/6.jpg"],
        "description": "CBee.ai is a webApp giving users access to Generative AI tools for Digital Marketers with features such as Text to Video, URL To Video, Google Drive video suggestions, video customisations and more, pioneering the field of automated portrait style social media video generation.\nThis webApp has been handed over and is currently being maintained by the CBee.ai team after its successful launch.",
        "url": "https://cbee.ai",
        "code_url": null,
        "links": [],
        "features": ["SEO Optimised", "Generative AI used to generate videos", "Highly customisable videos from the designs to the script"],
        "tech": ["Next.JS", "Typescript", "Python", "FastAPI", "GPT-3.5 API", "Azure Cognitive Services", "Azure Speech Services", "AWS S3 API", "Nginx", "Linux", "Google APIs"],
        "category": "Website"
    },
    {
        "datetime": "2024-01-01",
        "title": "Employee Conversational Training Module",
        "shorttitle": "traj",
        "images": ["/project-images/traj/1.jpg", "/project-images/traj/2.jpg"],
        "description": "This module was built as an improvement to the existing training process for new employees. The module is a chatbot that Guides the user through the training process through a hands on scenario conversation. It utilises the GPT-3.5 API to add highly sophisticated language processing and accurate scoring. The module is built to be highly configurable, allowing the admin to add, edit and delete questions and answers as needed.",
        "url": null,
        "code_url": null,
        "links": ["https://drive.google.com/file/d/1B-ZGhZnbu8_cdMqFM8pd7cv5MIy2-tgy/view?usp=sharing"],
        "features": ["Text to Speech", "Conversational and friendly interface", "Ability to add, edit and delete roleplays", "Completely integrated with existing MCQ infrastructure allowing for ease of adoption"],
        "tech": ["HTML", "CSS", "JavaScript", "Python", "Flask", "GPT-3.5 API", "MySQL"],
        "category": "Website"
    },
    {
        "datetime": "2024-01-01",
        "title": "Cleaning Supervision Module",
        "shorttitle": "dm",
        "images": ["/project-images/dm/1.jpg", "/project-images/dm/2.jpg", "/project-images/dm/3.jpg", "/project-images/dm/4.jpg"],
        "description": "This site was built for cleaning supervisors to use during their regular Cleaning contract with Dubai Municipality for various locations around Dubai. The site streamlines the process, giving supervisors an efficient way to record data and gives superiors an automated method to generate reports and oversee day to day operations easily.\nFulfilling the need to digitise a manual system, reducing data entry work massively and saving the company precious time.",
        "url": null,
        "code_url": null,
        "links": [],
        "features": ["Checklist Management", "Geotagging and timestamping checklist entries", "Highly configurable settings that allow administrators to add, edit and delete users, roles and locations", "Exporting the reports in excel in different necessary formats."],
        "tech": ["HTML", "CSS", "JavaScript", "Python", "Flask", "MySQL"],
        "category": "Website"
    },
    {
        "datetime": "2022-07-01",
        "title": "Prime FM Company Website",
        "shorttitle": "pfm-homepage",
        "images": ["/project-images/homepage/1.jpg", "/project-images/homepage/2.jpg", "/project-images/homepage/3.jpg"],
        "description": "This site was built for a new emerging FM company, the site quickly took first ranking in a google search for the terms \"Prime FM UAE\" and \"Prime FM\" due to excellent SEO optimisation. The site also features an Admin panel where the site owner can add his own updates to the site.",
        "url": "https://www.primefm-me.com",
        "code_url": null,
        "links": [],
        "features": ["SEO Optimised", "Google Captcha for forms", "Admin Panel"],
        "tech": ["HTML", "CSS", "JavaScript", "Python", "Flask", "MySQL"],
        "category": "Website"
    },
    {
        "datetime": "2022-08-01",
        "title": "Solar Panel Maintenance Module",
        "shorttitle": "solar",
        "images": ["/project-images/solar/1.jpg", "/project-images/solar/2.jpg", "/project-images/solar/3.jpg"],
        "description": "This site was built for maintenance employees to use during Solar panel maintence for villas. The company using this site received a contract from DEWA for 100+ villas and is seeking more. The site streamlines the process, giving employees an efficient way to record data and gives supervisors a smooth review process.\nHence digitising a system that would traditionally be manually written and transferred to excel. Reducing data entry work massively and saving the company precious time.",
        "url": null,
        "code_url": null,
        "links": [],
        "features": ["Simultaneous work order creation", "Pick up where you left off in the form (autosaving)", "Geotagging and timestamping images", "Taking and recording CLIent signature", "Exporting the reports in excel, including images", "Manage different view, edit, create permissions for different account types (Supervisors, Employees, CLIents)"],
        "tech": ["HTML", "CSS", "JavaScript", "Python", "Flask", "MySQL"],
        "category": "Website"
    },
    {
        "datetime": "2022-10-01",
        "title": "Building Checklist Module",
        "shorttitle": "building",
        "images": ["/project-images/building/1.jpg", "/project-images/building/2.jpg", "/project-images/building/3.jpg", "/project-images/building/4.jpg", "/project-images/building/5.jpg"],
        "description": "This site was built for maintenance employees to use during their daily checks on Building equipment in large buildings. It is currently in daily use on the field. It elminates the need to carry around a printed notepad checklist, and enables the ability to instantly generate reports and check daily work status. The data can also be filtered to build custom reports based on the need of the hour.\nThe Daily checklists are highly customisable, forms, buildings, units and categories can be added and removed as simply as adding or deleting a row/column from the database.",
        "url": null,
        "code_url": null,
        "links": [],
        "features": ["Daily Checklist creation for various properties", "Shows the list of units in the building per checklist", "Allows admins to generate and export (to excel) reports as needed (with filters)", "Option to view daily progress (Completed, ongoing, incomplete)", "Can easily add, remove or edit forms, units and buldings as needed with no changes in the API and frontend code.", "Manage different view, edit, create permissions for different account types (Supervisors, Employees)."],
        "tech": ["HTML", "CSS", "JavaScript", "Python", "Flask", "MySQL"],
        "category": "Website"
    },
    {
        "datetime": "2023-11-01",
        "title": "CIIED Website",
        "shorttitle": "ciiedpage",
        "images": ["/project-images/ciiedpage/1.jpg", "/project-images/ciiedpage/2.jpg", "/project-images/ciiedpage/3.jpg"],
        "description": "CIIED is the Centre for Incubation, Innovation & Entrepreneurship, Dubai, for BITS Pilani, Dubai Campus. As CIIED's Web Developer I built the Website, and I maintain and update it's content. I have made adding events (the most frequently updated part of the site) into a simple task by automating it with a JSON file.",
        "url": "https://ciied.netlify.App/",
        "code_url": null,
        "links": [],
        "features": ["SEO Optimised", "JSON Automation for quick and easy updation", "Clean and simple Design"],
        "tech": ["HTML", "CSS", "JavaScript"],
        "category": "Website"
    },
    {
        "datetime": "2023-12-01",
        "title": "Emissions Tracker",
        "shorttitle": "emissions",
        "images": ["/project-images/emissions/1.jpg", "/project-images/emissions/2.jpg", "/project-images/emissions/3.jpg"],
        "description": "It is a Carbon Emissions Tracker, as global warming intensifies and the threat grows larger, this Website serves as a great source of awareness, you can use it to keep track of your emissions, use the search bar to find a source of emissions and add it to your record. It may suprise users to know how large the emissions are even for simple tasks.",
        "url": "https://emissiontracker.netlify.App",
        "code_url": "https://github.com/Fir121/Carbon-Footprint-Tracker",
        "links": [],
        "features": [],
        "tech": ["HTML", "CSS", "JavaScript"],
        "category": "Website"
    },
    {
        "datetime": "2021-08-01",
        "title": "StreamGrounds",
        "shorttitle": "streamgrounds",
        "images": ["/project-images/streamgrounds/1.jpg", "/project-images/streamgrounds/2.jpg", "/project-images/streamgrounds/3.jpg", "/project-images/streamgrounds/4.jpg"],
        "description": "At StreamGrounds users can download torrents and store them, so they can watch them from any device just like NETFLIX (but without content limitations ;).\nUser accounts are linked to my service called TheGrounds with sign ups based on a referral system.\nScreenshots show a sample torrent of a public domain Charlie Chaplin movie torrent.\nCurrently the Website deletes movies after 14 days to save space since my home server (RPi 4) is limited.",
        "url": "https://thegrounds.pythonanywhere.com/streamgrounds",
        "code_url": null,
        "links": [],
        "features": ["Intuitive workflow", "Downloads sharing between users to eliminate initial download time", "Pick Up where you left off watching"],
        "tech": ["HTML", "CSS", "JavaScript", "Python", "Bash", "Flask", "Raspberry Pi", "Ngrok", "Nginx", "Linux"],
        "category": "Website"
    },
    {
        "datetime": "2021-09-01",
        "title": "FairGrounds",
        "shorttitle": "fairgrounds",
        "images": ["/project-images/fairgrounds/1.jpg", "/project-images/fairgrounds/2.jpg", "/project-images/fairgrounds/3.jpg", "/project-images/fairgrounds/4.jpg"],
        "description": "FairGrounds allows users to upload and share files with just a link. I built it based on the WeTransfer concept, but WeTransfer deletes the files after a week or so, FairGrounds has no such limitation.\nFairGrounds works amazingly fast for small to medium files, but due to server limitations big files may be slow.",
        "url": "https://thegrounds.pythonanywhere.com/fairgrounds",
        "code_url": null,
        "features": ["Automatic emails can be sent for sharing", "Links never expire", "Can send any file types, to combined sizes as large as 10GB"],
        "links": [],
        "tech": ["HTML", "CSS", "JavaScript", "Python", "Bash", "Flask", "Raspberry Pi", "Ngrok", "Nginx", "Linux"],
        "category": "Website"
    },
    {
        "datetime": "2021-12-01",
        "title": "Social",
        "shorttitle": "social",
        "images": ["/project-images/social/1.jpg", "/project-images/social/2.jpg", "/project-images/social/3.jpg"],
        "description": "Social is a fully functioning prototype for a truly Social, Social Network, basically a social Network where people can help their community.",
        "url": "https://thesocialnetwork.netlify.App/#/",
        "code_url": "https://github.com/Fir121/Social",
        "links": ["https://medium.com/@f20210116/journey-to-social-a-truly-social-social-network-fb17e6452d7f", "https://youtu.be/E62ho-K_emY"],
        "features": ["Sign Up, Log In", "A working posts feed and comments section", "Lists of volunteering opportunities and ability to \"volunteer now\""],
        "tech": ["Flutter", "Dart", "Flask", "Postman", "MySQL"],
        "category": "Website"
    },
    {
        "datetime": "2021-01-01",
        "title": "PharmaChain",
        "shorttitle": "pharmachain",
        "images": ["/project-images/pharmachain/1.jpg", "/project-images/pharmachain/2.jpg", "/project-images/pharmachain/3.jpg"],
        "description": "PharmaChain is a prototype of a mobile Application that allows you to order medicines with full transparency, and reliability.\nPharmaChain uses Blockchain technology to provide complete tracking and security over the entire process. It also keeps track of temperature and expiry conditions for pharmaceuticals and uses a smart contract to take action if needed.\nPharmaChain was a finalist at the Technocare E-Cell MUJ Hackathon.",
        "url": "https://pharmachain.pythonanywhere.com/",
        "code_url": null,
        "links": ["https://www.youtube.com/watch?v=TC9nzvURWAs"],
        "features": ["Blockchain based data storage for reliability in the supply chain", "Fully functioning order cart, checkout system", "Ability to add prescriptions and automate orders"],
        "tech": ["Flutter", "Dart", "Flask", "Blockchain"],
        "category": "App"
    },
    {
        "datetime": "2021-02-01",
        "title": "Scooty",
        "shorttitle": "scooty",
        "images": ["/project-images/scooty/1.jpg"],
        "description": "Scooty was an App built to solve an RTA (Roads and Transport Authority) Dubai problem with e-scooters.\nThe App promotes safe e-scooter driving, it can issue training and subsequently licenses. \nIt allows users to gain points for their rides based on their safety score.\nAdditionally, the prototype has a working computer vision helmet detection system.\nScooty won first place at the RTA Public Transport Hackathon 2022.",
        "url": null,
        "code_url": null,
        "links": ["https://drive.google.com/file/d/1h9Y0J2fnoCHTXmxT2g-JgtL-QE34j3eV/view?usp=sharing"],
        "features": [],
        "tech": ["Figma", "Python", "Ionic"],
        "category": "App"
    },
    {
        "datetime": "2020-01-01",
        "title": "TheUnderGround",
        "shorttitle": "theunderground",
        "images": ["/project-images/theunderground/1.jpg", "/project-images/theunderground/2.jpg", "/project-images/theunderground/3.jpg"],
        "description": "When WhatsApp changed their privacy features back in the peak of lockdown I took it personally, I took it upon myself to build an alternative for me and my friends which lead to the development of TheUnderGround, the first CLI software of TheGrounds. \nOver time it has developed several features. Initially it was a very basic software, with hit enter to update messages and http get based messaging, but later I hosted a python server in my raspberry pi 4 and using TCP sockets achieved real time messaging additionally, using a multithreading Approach I was able to achieve a CLI curses style input so messages can be printed at the same time as input was entered. \nTheUnderGround gave me a much deeper understanding of messaging, data encryption, and account management.",
        "url": "https://thegrounds.pythonanywhere.com/theunderground",
        "code_url": null,
        "links": [],
        "features": ["Real-time messaging", "Can send text, images, and audio", "Fun features such as funky, self-deleting, autocorrected messages, dad jokes etc", "Settings bar with several options: skins, message updates, initialisation settings etc", "Full Privacy!"],
        "tech": ["Python", "Flask", "MySQL", "Raspberry Pi"],
        "category": "CLI"
    },
    {
        "datetime": "2020-02-01",
        "title": "TheAboveGround",
        "shorttitle": "theaboveground",
        "images": ["/project-images/theaboveground/1.jpg", "/project-images/theaboveground/2.jpg", "/project-images/theaboveground/3.jpg"],
        "description": "TheAboveGround too was created in response to a rumoured privacy infringement during the pandemic, it is a CLI voice chatting software, since it’s so lightweight it’s great to use to chat with friends while gaming, multi-tasking or even just for casual chatting. \nIt can handle up to 10 people or more concurrently in a call, limited only due to sever bandwidth, server being a Raspberry Pi 4 at home, Additionally, people can text chat during the call. \nThis project was great to learn about UDP sockets, implemented with python.",
        "url": "https://thegrounds.pythonanywhere.com/theaboveground",
        "code_url": null,
        "links": [],
        "features": ["Real-time voice calls with several people", "Fully encrypted data over a UDP socket", "Very Lightweight yet still performs the same as Other voice chatting software such as zoom/google meet"],
        "tech": ["Python", "Raspberry Pi"],
        "category": "CLI"
    },
    {
        "datetime": "2020-03-01",
        "title": "TheMusicGround",
        "shorttitle": "themusicground",
        "images": ["/project-images/themusicground/1.jpg", "/project-images/themusicground/2.jpg", "/project-images/themusicground/3.jpg", "/project-images/themusicground/4.jpg"],
        "description": "TheMusicGround as the name suggests is a CLI software to listen to music (makes use of YouTube as a source). \nIt takes the help of several different music-based API’s to facilitate it’s many features. The python-vlc module helps in playing the audio seamlessly.",
        "url": "https://thegrounds.pythonanywhere.com/themusicground",
        "code_url": null,
        "links": [],
        "features": ["Search by Song, Artists, and Lyrics", "Custom Playlists based on your listening preferences", "Songs can be downloaded for offline mode", "Podcasts are available", "Web Radio stations are available from 100+ countries", "Shazam API allows for song recognition", "User Playlists can be shared", "Also has strong error handling and an error logger to catch the inevitable bugs for later debugging."],
        "tech": ["Python", "VLC", "FFmpeg", "Flask", "MySQL"],
        "category": "CLI"
    },
    {
        "datetime": "2023-06-01",
        "title": "Academic Planner",
        "shorttitle": "acplanner",
        "images": ["/project-images/acplanner/1.jpg", "/project-images/acplanner/2.jpg", "/project-images/acplanner/3.jpg", "/project-images/acplanner/4.jpg"],
        "description": "Students have very tight schedules, they are required to deal with multiple deadlines, exams, attendance criteria etc., due to this burden it is difficult for students to plan their Academics and still strike an optimal balance. The purpose of this project was to introduce an innovative solution that would combat this issue – An Academic Planner. Students may keep track of their courses, events, holidays, attendances, and grades over the course of a semester.\nBuilt with Java, with BPDC students in mind.",
        "url": null,
        "code_url": "https://github.com/Fir121/Academic_Planner",
        "links": [],
        "features": [],
        "tech": ["Java", "Java Swing"],
        "category": "GUI"
    },
    {
        "datetime": "2021-06-01",
        "title": "Currency Rates Tracker",
        "shorttitle": "currency",
        "images": ["/project-images/currency/1.jpg", "/project-images/currency/2.jpg", "/project-images/currency/3.jpg", "/project-images/currency/4.jpg"],
        "description": "Allows user to Track and visualise data of several currency types, from conversion to charts and live price updates.\nWon Second place at the Curtin Dubai Writing and Hackathon Competition 2021",
        "url": null,
        "code_url": null,
        "links": [],
        "features": [],
        "tech": ["Python", "Tkinter"],
        "category": "GUI"
    },
    {
        "datetime": "2020-06-01",
        "title": "Universal Converter",
        "shorttitle": "converter",
        "images": ["/project-images/converter/1.jpg", "/project-images/converter/2.jpg", "/project-images/converter/3.jpg"],
        "description": "Allows user to convert between several different units, under categories of Mass, Length, Speed, Temperature, Currency and Date.\nWon Third place at the Curtin Dubai Writing and Hackathon Competition 2020",
        "url": null,
        "code_url": "https://github.com/Fir121/Currency-Converter",
        "links": [],
        "features": [],
        "tech": ["Python", "Tkinter"],
        "category": "GUI"
    },
    {
        "datetime": "2020-08-01",
        "title": "Bank Account Manager",
        "shorttitle": "bank",
        "images": ["/project-images/bank/1.jpg", "/project-images/bank/2.jpg"],
        "description": "Users can manage their bank accounts, built with a MySQL connector, with basic encryption. For a school project.",
        "url": null,
        "code_url": null,
        "links": ["https://drive.google.com/file/d/1a_2T5aAfdFM6rzfHIdzLDwcqpsLLa7OX/view?usp=sharing"],
        "features": [],
        "tech": ["Python", "Tkinter"],
        "category": "GUI"
    },
    {
        "datetime": "2021-04-01",
        "title": "Contract Maker",
        "shorttitle": "contract",
        "images": ["/project-images/contract/1.jpg", "/project-images/contract/2.jpg"],
        "description": "Contract Maker is a telegram bot built to help a relative manage their property renting needs.\nThis bot was custom built so the user could generate contracts with a simple chatbot instead of a long process of manually entering all the data for each new tenant. \nAdditionally, the bot generates monthly income reports and sends a reminder a few weeks before each renewal via email.\nThis program has reduced time spent on contract creation by nearly 90% which is a testament to automation and it’s benefits.",
        "url": null,
        "code_url": null,
        "links": [],
        "features": ["Automatically calculates the ending date of the contract", "User can view any existing contracts as a pdf or a word file", "Photo scan feature allows the user to send a screenshot of the tenants aadhar/Other and the bot extracts the information"],
        "tech": ["Python", "Raspberry Pi", "Chatbot"],
        "category": "Other"
    },
    {
        "datetime": "2021-04-01",
        "title": "Test Reminder Bot",
        "shorttitle": "bits",
        "images": ["/project-images/bits/1.jpg"],
        "description": "I built bits test to remind me of upcoming quizzes, tests or assignments.\nBits_test bot allows me to add/delete courses and later view upcoming components.\nAdditionally it sends me an email a few days before any upcoming component.",
        "url": null,
        "code_url": null,
        "links": [],
        "features": [],
        "tech": ["Python", "Raspberry Pi", "Chatbot"],
        "category": "Other"
    },
].sort((a, b) => new Date(b.datetime).getTime() - new Date(a.datetime).getTime())